### ISSUE TITLE
pulumiverse_grafana python library gives AttirbuteError

### ISSUE THREAD

**Issue by m-mutti** [pulumiverse/pulumi-grafana#218]
# Error message:
```
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "D:\abc\k8s\k8s.infrastructure\abc_core_cluster\iac\__main__.py", line 403, in <module>
        import pulumiverse_grafana as grafana
      File "D:\abc\k8s\k8s.infrastructure\abc_core_cluster\iac\venv\Lib\site-packages\pulumiverse_grafana\__init__.py", line 29, in <module>
        from .get_cloud_ips import *
      File "D:\abc\k8s\k8s.infrastructure\abc_core_cluster\iac\venv\Lib\site-packages\pulumiverse_grafana\get_cloud_ips.py", line 139, in <module>
        def get_cloud_ips_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCloudIpsResult]:
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pulumi' has no attribute 'InvokeOutputOptions'
```

# Package versions I'm using
```
pulumi==3.138.0
pulumi_azure_native==2.70.0
pulumi_azuread==6.0.1
pulumi_kubernetes==4.18.3
pulumiverse_grafana==0.9.2
```

**Comment by ringods** [comment]
@m-mutti as a workaround, you require `pulumi==3.142.0` for this type to be found. 

I'm building a new version of the provider which will set the correct package version dependency, so keep an eye for v0.9.3 to be published.

**Comment by m-mutti** [comment]
Thanks. Resolved by manually upgrading
